if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_60cd2642e82d2',
	'title' => 'adicionales',
	'fields' => array(
		array(
			'key' => 'field_60cd2651badd0',
			'label' => 'Oral Natural',
			'name' => 'oral_natural',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Si' => 'Si',
				'No' => 'No',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60cd267cbadd1',
			'label' => 'Anal',
			'name' => 'anal',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Si' => 'Si',
				'No' => 'No',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60cd26a4badd2',
			'label' => '',
			'name' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_60cd192e62fbb',
	'title' => 'modelProfile',
	'fields' => array(
		array(
			'key' => 'field_60cd193772e4a',
			'label' => 'Talla de Busto',
			'name' => 'talla_de_busto',
			'type' => 'text',
			'instructions' => 'Ingrese la talla de busto de la modelo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_60cd23ff4ebb5',
			'label' => 'Edad',
			'name' => 'edad',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 21,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 18,
			'max' => 40,
			'step' => '',
		),
		array(
			'key' => 'field_60cd24274ebb6',
			'label' => 'Estatura',
			'name' => 'estatura',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'Mts',
			'min' => '',
			'max' => '2.0',
			'step' => '',
		),
		array(
			'key' => 'field_60cd244c4ebb8',
			'label' => 'Nacionalidad',
			'name' => 'nacionalidad',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_60cd245d4ebb9',
			'label' => 'Ciudad de origen',
			'name' => 'ciudad_de_origen',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_60cd24714ebba',
			'label' => 'Experiencia',
			'name' => 'experiencia',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Para estreno' => 'Para estreno',
				'Para segundo servicio' => 'Para segundo servicio',
				'Para tercer servicio' => 'Para tercer servicio',
				'Menos de un mes' => 'Menos de un mes',
				'Menos de tres meses' => 'Menos de tres meses',
				'Entre 3 y 6 meses' => 'Entre 3 y 6 meses',
				'Entre 6 meses y 1 año' => 'Entre 6 meses y 1 año',
				'Entre 1 año y 2 años' => 'Entre 1 año y 2 años',
				'Mas de 3 años de experiencia' => 'Mas de 3 años de experiencia',
			),
			'default_value' => 'Entre 3 y 6 meses',
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60cd24ffbeacf',
			'label' => 'Medidas',
			'name' => 'medidas',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_60cd2507bead0',
			'label' => 'Categoria de Porno',
			'name' => 'categoria_de_porno',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Milf' => 'Milf',
				'Lolita' => 'Lolita',
				'Gafufa' => 'Gafufa',
				'Big tits' => 'Big tits',
				'Natural Big Tits' => 'Natural Big Tits',
				'Gold Digger' => 'Gold Digger',
				'Negra' => 'Negra',
				'Flaca' => 'Flaca',
				'Alta' => 'Alta',
				'Morena' => 'Morena',
				'Culona' => 'Culona',
				'Caderona' => 'Caderona',
				'BBW' => 'BBW',
				'Pecosa' => 'Pecosa',
				'Rubia Natural' => 'Rubia Natural',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60cd257abead1',
			'label' => 'Color de Ojos',
			'name' => 'color_de_ojos',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Cafes' => 'Cafes',
				'Azules' => 'Azules',
				'Verdes' => 'Verdes',
				'MIel' => 'MIel',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60cd25acbead2',
			'label' => 'Color de Piel',
			'name' => 'color_de_piel',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Blanca' => 'Blanca',
				'Muy Blanca' => 'Muy Blanca',
				'Morena' => 'Morena',
				'Negra' => 'Negra',
				'Trigueña' => 'Trigueña',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60cd25d3bead3',
			'label' => 'Talla de Pantalon',
			'name' => 'talla_de_pantalon',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;